Repository treasure-data/td-client-java, pull requests merged in 2023-02, with the labels that each got.

#232 testlib: Bump littleproxy
  pom.xml
  src/test/java/com/treasuredata/client/TestProxyAccess.java
  src/test/java/com/treasuredata/client/TestSSLProxyAccess.java
Labels: dependencies

#244 Replace JSON.simple with already-inuse Jackson
  pom.xml
  src/main/java/com/treasuredata/client/TDClient.java
  src/main/java/com/treasuredata/client/model/TDColumn.java
  src/test/java/com/treasuredata/client/TestTDClient.java
Labels: enhancement, dependencies

#249 Update release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: chore

#252 Fixed the broken CircleCI status badge
  README.md
Labels: doc
